name: astro-webapps-course-dev-env

services:

  web_dev:
    build:
      context: .
      dockerfile: dockerfile-web
    image: astro-webapps-course-dev-img
    container_name: astro-webapps-course-dev-container
    user: node
    ports:
      - "3007:3000"
    volumes:
      - ../:/home/node/workspace:cached
      - ${HOME}/.local/share/pnpm:/home/node/.local/share/pnpm:cached
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "true"]
      interval: 30s
      timeout: 10s
      retries: 3

